#!/bin/bash
# BROWSER_SHORTCUT

if [ -n $1 ]; then
    URL=https://github.com/rhinstaller/anaconda-webui/pull/$1
else
    URL=https://github.com/rhinstaller/anaconda-webui/pulls
fi

firefox -new-tab $URL
