#!/bin/bash

# To add files to the filesystem just have updates directory with the files in
# the anaconda repository before running the script

set -x

LOCAL_ANACONDA_REPO=$(realpath ../anaconda)
RV_UPD_ANACONDA_REPO=${RV_UPD_ANACONDA_REPO:-$LOCAL_ANACONDA_REPO}
ANACONDA_UPDATES=${RV_UPD_ANACONDA_REPO}/updates.img
WORK_DIR=updupd

pushd ${RV_UPD_ANACONDA_REPO}
scripts/makeupdates
popd

cp ${ANACONDA_UPDATES} updates.anaconda.img

rm -rf ${WORK_DIR}
mkdir ${WORK_DIR}

pushd ${WORK_DIR}
gzip -dc ../updates.webui.img | cpio -id
tree . > ../tree.updates.webui.img.txt
gzip -dc ../updates.anaconda.img | cpio -idu
tree . > ../tree.updates.img.txt
find . | cpio -c -o | gzip -9cv > ../updates-fedora-rawhide.img
popd
